### ISSUE TITLE
The builder depends on internal use of `handlebars` that will be removed in Storybook 8.4

### ISSUE THREAD

**Issue by JReinhold** [rspack-contrib/storybook-rsbuild#136]
For Storybook 8.4 we're doing a lot of internal cleanup and optimisation (see https://github.com/storybookjs/storybook/issues/29038).

As part of [my work to replace the `express` dev-server with `polka`](https://github.com/storybookjs/storybook/pull/29230), I wanted to try out if that worked with RSBuild, because the server is exposed to the builders via the `start()` function. However I never got that far, because RSBuild fails with the following error in the latest alpha releases of Storybook `8.4.0`:

```
=> Failed to build the preview
TypeError: (0 , import_common.handlebars) is not a function
    at getVirtualModules (./node_modules/storybook-builder-rsbuild/dist/index.js:195:66)
    at async iframe_rsbuild_config_default (./node_modules/storybook-builder-rsbuild/dist/index.js:371:72)
    at async rsbuild (./node_modules/storybook-builder-rsbuild/dist/index.js:656:23)
    at async Module.start (./node_modules/storybook-builder-rsbuild/dist/index.js:691:18)
    at async storybookDevServer (./node_modules/@storybook/core/dist/core-server/index.cjs:37195:11)
    at async buildOrThrow (./node_modules/@storybook/core/dist/core-server/index.cjs:36205:12)
    at async buildDevStandalone (./node_modules/@storybook/core/dist/core-server/index.cjs:38385:78)
    at async withTelemetry (./node_modules/@storybook/core/dist/core-server/index.cjs:36950:12)
    at async dev (./node_modules/@storybook/core/dist/cli/bin/index.cjs:2877:3)
    at async r.<anonymous> (./node_modules/@storybook/core/dist/cli/bin/index.cjs:2929:74)
```

This is because we've removed `handlebars` from the Storybook `core/common` exports, as it was unnecessary. It was never intended to be used as a public API, but it's fair that you perhaps just copied the logic from the Webpack builder.

You should be able to to the same migration that @ndelangen we did for the Webpack builder in https://github.com/storybookjs/storybook/pull/29208. High-level, that PR:

1. converts the handlebar template to [a regular JS file](https://github.com/storybookjs/storybook/pull/29208/files#diff-761784ae3b06ad9d141a0ef83c40121679c12085b00a139f74d24de98440fada)
2. [uses `'{{someVariable}}'`](https://github.com/storybookjs/storybook/pull/29208/files#diff-761784ae3b06ad9d141a0ef83c40121679c12085b00a139f74d24de98440fadaR6) for stuff that needs replacement
3. [Uses regular `replaceAll()` calls](https://github.com/storybookjs/storybook/pull/29208/files#diff-4e3893b3d98bcc595f97737ef7c371ea29ec9af668edcdfa0e09025aab0bc90cR58-R74) to do the variable replacements.

**Comment by fi3ework** [comment]
Thanks @JReinhold for the kind remind. I'll do the same migration quickly.
