### ISSUE TITLE
Cache is required

### ISSUE THREAD

**Issue by binary64** [rspack-contrib/storybook-rsbuild#33]
Hi, I'm getting a strange error. How can I enable cache?
```
$ yarn nx run ui:export-storybook --skip-nx-cache --verbose
yarn run v1.22.18
$ cross-env NODE_OPTIONS=--max-old-space-size=16000 nx run ui:export-storybook --skip-nx-cache --verbose

> nx run ui:export-storybook

^[[44;1R

 NX  Storybook builder starting ...

info => Cleaning outputDir: \dist\storybook\ui
info => Loading presets
info => Building manager..
info => Manager built (334 ms)
info => Building preview..
info Addon-docs: using MDX3
info => Copying static files: c:\monorepo\node_modules\@storybook\manager\static at c:\monorepo\dist\storybook\ui\sb-common-assets
=> Failed to build the preview

 NX   Cache is required


Error: Cache is required
    at iframe_rsbuild_config_default (c:\monorepo\node_modules\storybook-builder-rsbuild\dist\index.js:363:11)
    at async rsbuild (c:\monorepo\node_modules\storybook-builder-rsbuild\dist\index.js:523:25)
    at async Module.build (c:\monorepo\node_modules\storybook-builder-rsbuild\dist\index.js:605:18)
    at async Promise.all (index 0)
    at async buildStaticStandalone (c:\monorepo\node_modules\@storybook\core-server\dist\index.js:61:2295)
    at async buildStorybookExecutor (c:\monorepo\node_modules\@nx\storybook\src\executors\build-storybook\build-storybook.impl.js:14:5)
    at async promiseToIterator (c:\monorepo\NODE_M~1\nx\src\command-line\run\run.js:32:11)
    at async getLastValueFromAsyncIterableIterator (c:\monorepo\NODE_M~1\nx\src\utils\async-iterator.js:13:19)
    at async iteratorToProcessStatusCode (c:\monorepo\NODE_M~1\nx\src\command-line\run\run.js:43:29)
    at async handleErrors (c:\monorepo\NODE_M~1\nx\src\utils\params.js:9:16)

——————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 NX   Running target export-storybook for project ui failed

Failed tasks:

- ui:export-storybook


```

**Comment by fi3ework** [comment]
Nx support needed.

**Comment by fi3ework** [comment]
@binary64  Could you provide the Storybook related Nx related configuration?

**Comment by xvalentino** [comment]
I was running into the same cache error.

However when creating a reproduction repo, it seems to work! 🥳 

https://github.com/xvalentino/rspack-storybook-reprod

I have a few differences in versions/configuration so I'll investigate more to see if I can find whats causing this cache error.

**Comment by codewreaker** [comment]
fixed mine by calling storybook directly instead of using the @nx/storybook:storybook executor and in the rsbuildFinal point your tsConfigPath to the project's typescript so it can resolve your paths. Finally don't forget to add addon-docs to resolve mdx files. Will post the code latwr

**Comment by codewreaker** [comment]
```json
//in project.json targets
"storybook":{
    "executor":"nx:run-commands",
    "options": {
        "commands": "storybook dev -c [configpath]"
    }
}
```


```ts
//in .storybook/main.ts
const config:StorybookConfig = {
    //... rest of code
    rsbuildFinal: async (config)=>{
        return mergeRsbuildConfig(config, {
            source:{
                tsconfigPath: '[path to tsonfig with path aliases]'
            }
        })
    }
}
```
