### ISSUE TITLE
error binding.JsResolverFactory is not a constructor

### ISSUE THREAD

**Issue by abenhamdine** [rspack-contrib/storybook-rsbuild#41]
I try to migrate from storybook/vite to storybook with rsbuild but I run into a build error : 

excerp of package.json : 

```json
"@rsbuild/core": "1.0.1-beta.0",
    "@rsbuild/plugin-eslint": "1.0.0",
    "@rsbuild/plugin-react": "1.0.1-beta.0",
    "@rsbuild/plugin-type-check": "1.0.1-beta.0",
    "@rsdoctor/rspack-plugin": "^0.3.7",
    "@storybook/addon-essentials": "8.2.2",
    "@storybook/addon-interactions": "8.2.2",
    "@storybook/addon-links": "8.2.2",
    "@storybook/addon-onboarding": "8.2.2",
    "@storybook/blocks": "8.2.2",
    "@storybook/react": "8.2.2",
    "@storybook/react-vite": "8.2.2",
    "@storybook/test": "8.2.2",
    "@storybook/test-runner": "0.19.0",
    "msw-storybook-addon": "2.0.3",
    "playwright": "1.45.1",
    "react-test-renderer": "18.3.1",
    "storybook": "8.2.2",
    "storybook-addon-manual-mocks": "1.0.4",
    "storybook-react-rsbuild": "0.0.7",
    "storybook-addon-remix-react-router": "3.0.0",
```

storybook/main.ts

```ts
import { StorybookConfig } from 'storybook-react-rsbuild'

const config: StorybookConfig = {
  stories: [
    "../src/**/*.stories.@(ts|tsx)"
  ],
  addons: [
    "@storybook/addon-links",
    "@storybook/addon-essentials",
    "@storybook/addon-onboarding",
    "@storybook/addon-interactions",
    {
      name: "storybook-addon-manual-mocks/vite",
      options: {
        mocksFolder: "mocks",
      }
    },
    'storybook-addon-remix-react-router',
  ],
  framework: {
    name: 'storybook-react-rsbuild',
    options: {}
  },
  rsbuildFinal: (config) => {
    // see https://github.com/rspack-contrib/storybook-rsbuild#customize-the-rsbuild-config
    // Customize the final Rsbuild config here
    return config;
  },
  staticDirs: ['../public'],
  docs: {
    defaultName: "Docs",
    docsMode: false,
    autodocs: false,
  },
}

export default config
```

rsbuild config : 
```ts
import { defineConfig } from '@rsbuild/core'
import { pluginReact } from '@rsbuild/plugin-react'
import { RsdoctorRspackPlugin } from '@rsdoctor/rspack-plugin'
import { pluginTypeCheck } from '@rsbuild/plugin-type-check'
import { pluginEslint } from '@rsbuild/plugin-eslint'

const shouldUseRsdoctor = process.env.RSDOCTOR === 'true'

export default defineConfig({
  server: {
    port: 3001,
  },
  html: {
    title: "Application paie",
  },
  source: {
    entry: {
      index: './src/index.tsx',
    }
  },
  output: {
    distPath: {
      root: 'build'
    },
    cleanDistPath: true
  },
  plugins: [
    /** désactivé car prend trop de mémoire, souvent OOM */
    pluginTypeCheck({ enable: false }),
    /** désactivé car prend presque 30s lors du build */
    pluginEslint({ enable: false }),
    pluginReact()
  ],
  tools: {
    rspack(config, { appendPlugins }) {
      // Only register the plugin when RSDOCTOR is true, as the plugin will increase the build time.
      if (shouldUseRsdoctor) {
        appendPlugins(
          new RsdoctorRspackPlugin({
            // voir https://rsdoctor.dev/guide/usage/rule-config pour la configuration des règles
            linter: {
              //  When set to `'Error'`, all rules will be executed
              level: 'Error',
              extends: [],
              rules: {
                'default-import-check': 'on',
                'duplicate-package': 'on',
                'loader-performance-optimization': 'on',
                // par défaut, c'est ES5, ce qui est trop bas pour notre app
                // et on ne peut changer que pour ES6 (trop bas aussi) ou ES7+ (tout ce qui ES7 ou plus) donc aucun intéret à garder la règle
                'ecma-version-check': "off",
              },
            },
          })
        )
      }
      config.experiments = {
        ...(config.experiments ?? {}),
        // https://www.rspack.dev/config/experiments#experimentslazycompilation
        // désactivé car ne semble pas fonctionner correctement
        lazyCompilation: false
      }
      return config
    }
  }
})

```

with this command
`cross-env NODE_OPTIONS=--max-old-space-size=8192 storybook dev -p 6006`
I get the following error : 

```
info => Serving static files from ./.\public at /
info => Starting manager..
info => Starting preview..
info Addon-docs: using MDX3
=> Failed to build the preview
TypeError: binding.JsResolverFactory is not a constructor
    at new ResolverFactory (.\node_modules\@rspack\core\dist\ResolverFactory.js:47:64)
    at new Compiler (.\node_modules\@rspack\core\dist\Compiler.js:148:32)
    at createCompiler (.\node_modules\@rspack\core\dist\rspack.js:44:22)
    at create (.\node_modules\@rspack\core\dist\rspack.js:89:26)
    at rspack (.\node_modules\@rspack\core\dist\rspack.js:115:37)
    at createCompiler (.\node_modules\@rsbuild\core\dist\index.cjs:2698:73)
    at async createDevMiddleware (.\node_modules\@rsbuild\core\dist\index.cjs:2771:16)
    at async startCompile (.\node_modules\@rsbuild\core\dist\index.cjs:4261:41)
    at async createDevServer (.\node_modules\@rsbuild\core\dist\index.cjs:4306:45)
    at async Module.start (.\node_modules\storybook-builder-rsbuild\dist\index.js:622:25)

WARN Broken build, fix the error above.
```

**Comment by fi3ework** [comment]
I'm not sure what caused the error. Could you please provide a minimal reproduction, or comment some plugins to bisect what plugin or config raised the error?

**Comment by yf-yang** [comment]
Looks like package version mismatch.
maybe a package lock file could help. The error may show you are using @rspack/binding 1.0.0 alpha and @@rspack/binding-win-xxx 0.x

**Comment by fi3ework** [comment]
Could try deleting node_modules and re-install the deps again.

**Comment by abenhamdine** [comment]
Thx for the hints.
I deleted node_modules and lock file, and re-installed everything, and this message is gone.
I have another error, but I will create a separate issue for clarity.
