### ISSUE TITLE
ReferenceError: React is not defined

### ISSUE THREAD

**Issue by ShaneYu** [rspack-contrib/storybook-rsbuild#79]
When using `storybook-react-rsbuild` in my react component library project, I am getting an error as below when trying to view any component story in storybook. The storybook UI renders, but would appear the canvas rendering fails.

Error encountered:
```
ReferenceError: React is not defined
    at Button (http://localhost:3000/static/js/async/button-stories-button-stories.iframe.bundle.js:73:5)
    at renderWithHooks (http://localhost:3000/static/js/vendors-node_modules_pnpm_rspack_core_1_0_0__swc_helpers_0_5_12_node_modules_rspack_core_dist-29fc0e.iframe.bundle.js:22105:18)
    at mountIndeterminateComponent (http://localhost:3000/static/js/vendors-node_modules_pnpm_rspack_core_1_0_0__swc_helpers_0_5_12_node_modules_rspack_core_dist-29fc0e.iframe.bundle.js:26717:13)
    at beginWork (http://localhost:3000/static/js/vendors-node_modules_pnpm_rspack_core_1_0_0__swc_helpers_0_5_12_node_modules_rspack_core_dist-29fc0e.iframe.bundle.js:28240:16)
    at beginWork$1 (http://localhost:3000/static/js/vendors-node_modules_pnpm_rspack_core_1_0_0__swc_helpers_0_5_12_node_modules_rspack_core_dist-29fc0e.iframe.bundle.js:34079:14)
    at performUnitOfWork (http://localhost:3000/static/js/vendors-node_modules_pnpm_rspack_core_1_0_0__swc_helpers_0_5_12_node_modules_rspack_core_dist-29fc0e.iframe.bundle.js:33213:12)
    at workLoopSync (http://localhost:3000/static/js/vendors-node_modules_pnpm_rspack_core_1_0_0__swc_helpers_0_5_12_node_modules_rspack_core_dist-29fc0e.iframe.bundle.js:33119:5)
    at renderRootSync (http://localhost:3000/static/js/vendors-node_modules_pnpm_rspack_core_1_0_0__swc_helpers_0_5_12_node_modules_rspack_core_dist-29fc0e.iframe.bundle.js:33087:7)
    at recoverFromConcurrentError (http://localhost:3000/static/js/vendors-node_modules_pnpm_rspack_core_1_0_0__swc_helpers_0_5_12_node_modules_rspack_core_dist-29fc0e.iframe.bundle.js:32503:20)
    at performConcurrentWorkOnRoot (http://localhost:3000/static/js/vendors-node_modules_pnpm_rspack_core_1_0_0__swc_helpers_0_5_12_node_modules_rspack_core_dist-29fc0e.iframe.bundle.js:32403:22)
```

To help with this issue, I've raised a minimal replication repo here:
https://github.com/ShaneYu/storybook-react-rsbuild-issue

Screenshot of storybook in action at time of error:
![image](https://github.com/user-attachments/assets/f8097c7b-a022-40e4-82e1-8196402ba548)

Version and package info:
```
System:
    OS: Windows 11 10.0.22631
    CPU: (32) x64 AMD Ryzen 9 7950X 16-Core Processor
    Memory: 1.82 GB / 31.21 GB

  Browsers:
    Edge: Chromium (127.0.2651.86)
    Internet Explorer: 11.0.22621.3527

  npmPackages:
    storybook-react-rsbuild: ^0.0.14 => 0.0.14
    @rsbuild/core: 1.0.1-rc.2 => 1.0.1-rc.2
    @storybook/addon-essentials: ^8.2.9 => 8.2.9
    @storybook/addon-interactions: ^8.2.9 => 8.2.9
    @storybook/addon-links: ^8.2.9 => 8.2.9
    @storybook/addon-onboarding: ^8.2.9 => 8.2.9
    @storybook/blocks: ^8.2.9 => 8.2.9
    @storybook/manager-api: ^8.2.9 => 8.2.9
    @storybook/react: ^8.2.9 => 8.2.9
    @storybook/test: ^8.2.9 => 8.2.9
    @storybook/theming: ^8.2.9 => 8.2.9
```

Please let me know if there is anything else you require to help investigate this issue? I've had a play around, but no matter what I do I simply cannot get it to work, always the same `React is not defined` error in the canvas.

Thank you 🙏

**Comment by ShaneYu** [comment]
So after having a good old fiddle I've discovered that I need to include `import React from 'react';` import in my component files, like the `button.tsx` and `alert.tsx`.

Once this is done, then it all works fine, however I've not had to include that import previously in any of my other react projects. I assume somehow it's added globally automatically?

Is it possible to remove the need for adding this import to every component file? Or is it recommended for some reason to include it?

**Comment by ShaneYu** [comment]
Never mind, found my answer to the above question also.

Would appear that React introduced a feature where JSX automatically handled it and so you did not need to use the import statement everywhere.

> With the new transform, you can use JSX without importing React.

My guess is this is something that needs to be addressed in rsbuild itself, I'll dig around there instead.
Since I've resolved all my issues, I'll mark this as closed.
